#!/usr/bin/python3
import functools
import ipaddress
import os
import subprocess


def write_access_conf(raw, conf_file='/etc/nginx/access.conf'):
    addresses = list(extract_addresses(raw))
    with open(conf_file, 'w') as f:
        write = functools.partial(print, file=f)
        write('# generated by Docker entrypoint script')

        if addresses:
            for addr in addresses:
                write('allow {};'.format(addr.compressed))
            write('deny all;')


def extract_addresses(raw):
    for addr in raw.split():
        if '-' in addr:
            start, end = addr.split('-', 1)
            yield from ipaddress.summarize_address_range(ipaddress.ip_address(start), ipaddress.ip_address(end))
        else:
            yield ipaddress.ip_network(addr)


def main():
    write_access_conf(os.environ.get('IP_WHITELIST', ''))

    GLOBAL_DIRECTIVES='daemon off;'
    subprocess.check_call(['/usr/local/bin/header_config.py'])
    subprocess.check_call(['nginx', '-t', '-g', GLOBAL_DIRECTIVES])
    os.execvp('nginx', ['nginx', '-g', GLOBAL_DIRECTIVES])


if __name__ == '__main__':
    main()
